#!/usr/bin/env bash
# Script to Install nginx on web server; Nginx should be listening on port 80
# 	   curl http://52.86.78.224/ -> returns string "Hello World!"
#	   curl http://52.86.78.224/ -> returns header info

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx start
