#!/usr/bin/env bash
#The script configures a server,to fix the nginx listening port
sudo sed -i 's/listen 8080/listen 80/g' /etc/nginx/sites-enabled/default
sudo sed -i 's/listen \[::\]:8080/listen \[::\]:80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart