#!/usr/bin/env bash
#Script to configure a server,to fix the nginx listening port
sed -i 's/listen 8080/listen 80/g' /etc/nginx/sites-enabled/default
sed -i 's/listen \[::\]:8080/listen \[::\]:80/g' /etc/nginx/sites-enabled/default
service nginx restart