#!/usr/bin/env bash
# script displays numbers from 1 to 100:
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# otherwise, displays the number in a list format

for ((j=1; j <= 100; j++))
do
	if ((j%3==0 && j%5==0))
	then
		echo FizzBuzz
	elif ((j%3==0))
	then
		echo Fizz
	elif ((j%5==0))
	then
		echo Buzz
	else
		echo "$j"
	fi
done
