#!/usr/bin/env bash
# script displays the contents of '/etc/passwd'
# Only the username, user 1d, & user home directory path is displayed

while read -r password
do
	echo "$password" | cut -d ":" -f 1,3,6
done < /etc/passwd
