#!/usr/bin/env bash
# script displays Best School 10 times, but for the 9th iteration,
# displays Best School and then Hi on a new-line
j=1
while ((j <= 10))
do
	echo "Best School"

	if [[ $j -eq 9 ]]
	then
		echo "Hi"
	fi

	j=$((j+1))
done
