#!/usr/bin/env bash
# script displays numbers from 1 to 20 &:
# displays 4 and then "bad luck from china" for the 4th loop iteration
# displays 9 and then "bad luck from Japan" for the 9th iteration
# displays 17 and then "bad luck from Italy" for the 17th iteration
k=1
while ((k <= 20))
do
	echo $k

	case $k in

		4)
			echo "bad luck from China"
			;;

		9)
			echo "bad luck from Japan"
			;;

		17)
			echo "bad luck from Italy"
			;;
	esac

	k=$((k+1))
done
