#!/usr/bin/env bash
# Script fixs container given to run as nginx user and listens on all active IPs on port 8080

# nginx config file update with user 'nginx'
sudo sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf

# permissions and change owner of config file
chmod 700 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf

# nginx file to listen to 8080 Update
sudo sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default

pkill apache2
sudo -u nginx service nginx restart
